FROM alpine:3.23 AS builder

# Temporary root directory for build output
ENV DEST_DIR=/tmp/dest

COPY . /tmp/repo
RUN set -x \
 # Build environment setup
 && apk add --no-cache --virtual .build-deps \
      build-base \
      cmake \
      c-ares-dev \
      libcap \
      libev-dev \
      libsodium-dev \
      linux-headers \
      mbedtls-dev \
      pcre2-dev \
 # Build & install
 && cd /tmp/repo \
 && mkdir -p build && cd build \
 && cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_TESTING=OFF -DWITH_STATIC=OFF -DCMAKE_BUILD_TYPE=Release \
 && make -j$(getconf _NPROCESSORS_ONLN) \
 && mkdir -p ${DEST_DIR} \
 && make install DESTDIR=${DEST_DIR} \
 && cd ${DEST_DIR}/usr/local/bin \
 && ls ${DEST_DIR}/usr/local/bin/ss-* | xargs -n1 setcap cap_net_bind_service+ep \
 && strip $(scanelf --nobanner -E ET_DYN -E ET_EXEC ${DEST_DIR}/usr/local/bin/ss-* | awk '{print $2}')

# Final runtime environment
FROM alpine:3.23
LABEL maintainer="kev <noreply@datageek.info>, Sah <contact@leesah.name>, vndroid <waveworkshop@outlook.com>"

ENV SERVER_ADDR=0.0.0.0
ENV SERVER_PORT=8388
ENV PASSWORD=
ENV METHOD=aes-256-gcm
ENV TIMEOUT=300
ENV DNS_ADDRS="8.8.8.8,8.8.4.4"
ENV TZ=UTC
ENV ARGS=

# Import build artifacts from the builder stage
COPY --from=builder /tmp/dest/ /

RUN set -x \
 # Runtime dependencies setup
 && apk add --no-cache \
      ca-certificates \
      rng-tools \
      tzdata \
      $(scanelf --needed --nobanner /usr/local/bin/ss-* \
      | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
      | sort -u)

COPY ./docker/alpine/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 8388

STOPSIGNAL SIGINT

CMD ["ss-server"]
